* Objetivos generales y competencias
   Según el RD de DAM (RD 450/2010, de 16 de abril) "La formación del módulo contribuye a alcanzar los objetivos generales b), e), i), j), l), n) y ñ) del ciclo formativo y las competencias b), e), i), j), l), n), ñ), t) y w) del título."
** Objetivos generales (RD 450/2010, de 16 de julio, por el que se establece el título de DAM - artículo 9)
   - b) Identificar las necesidades de seguridad analizando vulnerabilidades y verificando el plan preestablecido para aplicar técnicas y procedimientos relacionados con la seguridad en el sistema.

   - e) Seleccionar y emplear lenguajes, herramientas y librerías, interpretando las especificaciones para desarrollar aplicaciones multiplataforma con acceso a bases de datos.

   - i) Seleccionar y emplear técnicas, motores y entornos de desarrollo, evaluando sus posibilidades, para participar en el desarrollo de juegos y aplicaciones en el ámbito del entretenimiento.

   - j) Seleccionar y emplear técnicas, lenguajes y entornos de desarrollo, evaluando sus posibilidades, para desarrollar aplicaciones en teléfonos, PDA y otros dispositivos móviles.

   - l) Valorar y emplear herramientas específicas, atendiendo a la estructura de los contenidos, para crear tutoriales, manuales de usuario y otros documentos asociados a una aplicación.

   - n) Analizar y aplicar técnicas y librerías específicas, simulando diferentes escenarios, para desarrollar aplicaciones capaces de ofrecer servicios en red.

   - ñ) Analizar y aplicar técnicas y librerías de programación, evaluando su funcionalidad para desarrollar aplicaciones multiproceso y multihilo.

** Competencias profesionales, personales y sociales (RD 450/2010, de 16 de abril, por el que se establece el título de DAM - artículo 5)
   - b) Aplicar técnicas y procedimientos relacionados con la seguridad en sistemas, servicios y aplicaciones, cumpliendo el plan de seguridad.

   - e) Desarrollar aplicaciones multiplataforma con acceso a bases de datos utilizando lenguajes, librerías y herramientas adecuados a las especificaciones.

   - i) Participar en el desarrollo de juegos y aplicaciones en el ámbito del entretenimiento y la educación empleando técnicas, motores y entornos de desarrollo específicos.

   - j) Desarrollar aplicaciones para teléfonos, PDA y otros dispositivos móviles empleando técnicas y entornos de desarrollo específicos.

   - l) Crear tutoriales, manuales de usuario, de instalación, de configuración y de administración, empleando herramientas específicas.

   - n) Desarrollar aplicaciones multiproceso y multihilo empleando librerías y técnicas de programación específicas.

   - ñ) Desarrollar aplicaciones capaces de ofrecer servicios en red empleando mecanismos de comunicación.

   - t) Establecer vías eficaces de relación profesional y comunicación con sus superiores, compañeros y subordinados, respetando la autonomía y competencias de las distintas personas.

   - w) Mantener el espíritu de innovación y actualización en el ámbito de su trabajo para adaptarse a los cambios tecnológicos y organizativos de su entorno profesional.


* Resultados de aprendizaje y criterios de evaluación
** RA1. Desarrolla aplicaciones compuestas por varios procesos reconociendo y aplicando principios de programación paralela.
*** Criterios de evaluación
- a) Se han reconocido las características de la programación concurrente y sus ámbitos de aplicación.
- b) Se han identificado las diferencias entre programación paralela y programación distribuida, sus ventajas e inconvenientes.
- c) Se han analizado las características de los procesos y de su ejecución por el sistema operativo.
- d) Se han caracterizado los hilos de ejecución y descrito su relación con los procesos.
- e) Se han utilizado clases para programar aplicaciones que crean subprocesos.
- f) Se han utilizado mecanismos para sincronizar y obtener el valor devuelto por los subprocesos iniciados.
- g) Se han desarrollado aplicaciones que gestionen y utilicen procesos para la ejecución de varias tareas en paralelo.
- h) Se han depurado y documentado las aplicaciones desarrolladas.
  
** RA2. Desarrolla aplicaciones compuestas por varios hilos de ejecución analizando y aplicando librerías específicas del lenguaje de programación.
*** Criterios de evaluacion
- a) Se han identificado situaciones en las que resulte útil la utilización de varios hilos en un programa.
- b) Se han reconocido los mecanismos para crear, iniciar y finalizar hilos.
- c) Se han programado aplicaciones que implementen varios hilos.
- d) Se han identificado los posibles estados de ejecución de un hilo y programado aplicaciones que los gestionen.
- e) Se han utilizado mecanismos para compartir información entre varios hilos de un mismo proceso.
- f) Se han desarrollado programas formados por varios hilos sincronizados mediante técnicas específicas.
- g) Se ha establecido y controlado la prioridad de cada uno de los hilos de ejecución.
- h) Se han depurado y documentado los programas desarrollados.

** RA3. Programa mecanismos de comunicación en red empleando sockets y analizando el escenario de ejecución.
*** Criterios de evaluación
- a) Se han identificado escenarios que precisan establecer comunicación en red entre varias aplicaciones.
- b) Se han identificado los roles de cliente y de servidor y sus funciones asociadas.
- c) Se han reconocido librerías y mecanismos del lenguaje de programación que permiten programar aplicaciones en red.
- d) Se ha analizado el concepto de socket, sus tipos y características.
- e) Se han utilizado sockets para programar una aplicación cliente que se comunique con un servidor.
- f) Se ha desarrollado una aplicación servidor en red y verificado su funcionamiento.
- g) Se han desarrollado aplicaciones que utilizan sockets para intercambiar información.
- h) Se han utilizado hilos para implementar los procedimientos de las aplicaciones relativos a la comunicación en red.

** RA4. Desarrolla aplicaciones que ofrecen servicios en red, utilizando librerías de clases y aplicando criterios de eficiencia y disponibilidad.
*** Criterios de evaluación
- a) Se han analizado librerías que permitan implementar protocolos estándar de comunicación en red.
- b) Se han programado clientes de protocolos estándar de comunicaciones y verificado su funcionamiento.
- c) Se han desarrollado y probado servicios de comunicación en red.
- d) Se han analizado los requerimientos necesarios para crear servicios capaces de gestionar varios clientes concurrentes.
- e) Se han incorporado mecanismos para posibilitar la comunicación simultánea de varios clientes con el servicio.
- f) Se ha verificado la disponibilidad del servicio.
- g) Se han depurado y documentado las aplicaciones desarrolladas.

** RA5. Protege las aplicaciones y los datos definiendo y aplicando criterios de seguridad en el acceso, almacenamiento y transmisión de la información.
*** Criterios de evaluación
- a) Se han identificado y aplicado principios y prácticas de programación segura.
- b) Se han analizado las principales técnicas y prácticas criptográficas.
- c) Se han definido e implantado políticas de seguridad para limitar y controlar el acceso de los usuarios a las aplicaciones desarrolladas.
- d) Se han utilizado esquemas de seguridad basados en roles.
- e) Se han empleado algoritmos criptográficos para proteger el acceso a la información almacenada.
- f) Se han identificado métodos para asegurar la información transmitida.
- g) Se han desarrollado aplicaciones que utilicen sockets seguros para la transmisión de información.
- h) Se han depurado y documentado las aplicaciones desarrolladas.
