* 1.- Programación multiproceso
** RA1. Desarrolla aplicaciones compuestas por varios procesos reconociendo y aplicando principios de programación paralela.
*** Criterios de evaluación: a, b, c, d, e, f, g, h
    - a) Se han reconocido las características de la programación concurrente y sus ámbitos de aplicación.
    - b) Se han identificado las diferencias entre programación paralela y programación distribuida, sus ventajas e inconvenientes.
    - c) Se han analizado las características de los procesos y de su ejecución por el sistema operativo.
    - d) Se han caracterizado los hilos de ejecución y descrito su relación con los procesos.
    - e) Se han utilizado clases para programar aplicaciones que crean subprocesos.
    - f) Se han utilizado mecanismos para sincronizar y obtener el valor devuelto por los subprocesos iniciados.
    - g) Se han desarrollado aplicaciones que gestionen y utilicen procesos para la ejecución de varias tareas en paralelo.
    - h) Se han depurado y documentado las aplicaciones desarrolladas.
*** Objetivos generales: b, e, i, j, n, ñ
*** Competencias: n, t, w
